version: 2
project_name: session-proxy

builds:
  - env:
      - CGO_ENABLED=0
    dir: ./cmd/session-proxy
    binary: session-proxy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    ignore:
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: mips64
      - goos: darwin
        goarch: mips64le
      - goos: windows
        goarch: mips
      - goos: windows
        goarch: mipsle
      - goos: windows
        goarch: mips64
      - goos: windows
        goarch: mips64le
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: 
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: 
          - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/hanschad/session-proxy:{{ .Tag }}-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

  - image_templates:
      - "ghcr.io/hanschad/session-proxy:{{ .Tag }}-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

docker_manifests:
  - name_template: "ghcr.io/hanschad/session-proxy:{{ .Tag }}"
    image_templates:
      - "ghcr.io/hanschad/session-proxy:{{ .Tag }}-amd64"
      - "ghcr.io/hanschad/session-proxy:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/hanschad/session-proxy:latest"
    image_templates:
      - "ghcr.io/hanschad/session-proxy:{{ .Tag }}-amd64"
      - "ghcr.io/hanschad/session-proxy:{{ .Tag }}-arm64"
