version: 2
project_name: session-proxy

builds:
  - env:
      - CGO_ENABLED=0
    dir: ./cmd/session-proxy
    binary: session-proxy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    ignore:
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: mips64
      - goos: darwin
        goarch: mips64le
      - goos: windows
        goarch: mips
      - goos: windows
        goarch: mipsle
      - goos: windows
        goarch: mips64
      - goos: windows
        goarch: mips64le
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: 
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: 
          - zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
